# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccb65f4f5d6a88c27621866f2b0f4ae4dcd7627e6cfd7f628ccbc85f3aca08349a5005a668d43e4327aff54791d98f4a035fe97457b4fde260b0fc15082cdaef

test:
  secret_key_base: 3c3dc6b35465528a0cabe53a7606270f72ce8d5a5e195ea036008bfa18a3976b33821f9557b681b419eae19de2adc6d35e1e5e6f50f9bec32b0a38810166d47d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
